### ISSUE TITLE
Request: Multiplayer Support Show Where Others Are.

### ISSUE THREAD

**Issue by KaneHart** [Vectron/mapwriter#1]
This has been a long time request by my community is a feature that allows you to see everyone on the server. Great for those small tight communities. But we don't want the xray style of where the client sees it but rather simple server side mod that would show you where other players are no matter their distance.

Thanks.

**Comment by Vectron** [comment]
you mean a player radar?

**Comment by KaneHart** [comment]
yes but server side one where has a couple options and you can see players the entire world any dimension etc. None of this client side only ones that everyone has.

**Comment by Vectron** [comment]
hmmm i have a addon for mapwriter witch does the normal player rader. i might update it for a more server wide and then release it.

**Comment by Vectron** [comment]
i made a small mod that adds a overlay to mapwriter wich shows players on the map and minimaps.
if you also install it server side you can see the players no matter where they are in the world.

https://www.dropbox.com/s/glbmxbjlolo5wxq/MWEntityRadar-1.7.10-0.3.0.jar?dl=0

**Comment by KaneHart** [comment]
Thanks I hit another bug before I could even test this and it's without this before I can give it a try.

**Comment by KaneHart** [comment]
This is been a good day this also works well :) http://i.imgur.com/PUo4hHn.png

**Comment by Vectron** [comment]
glad to hear that, i will make a seperate page for the addon when i find some time again.
