### ISSUE TITLE
Pressing 'M' causes client crash [2.1.10]

### ISSUE THREAD

**Issue by steveowashere** [Vectron/mapwriter#13]
Just updated from 2.1.7 to 2.1.10 and now when I press 'M' I get a client crash with the follow problem: 

"[10:09:39] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NoSuchFieldError: isKeyBindingPressed"

Full log: https://paste.ee/p/Eia0B

FTB Infinity with added mods. Full list in crash log. 

Downgrading back to 2.1.7 fixes the problem, will test with other versions. 

Update: Can confirm this is not an issue on 2.1.9.

**Comment by Vectron** [comment]
You have to update not enough Keys to the latest version to use the 2.1.10 version.

Maybe i should check for the right nek version....

**Comment by steveowashere** [comment]
Ah okay. Updating NEK fixes the issue. A version checker might be a nice feature to have :)
