### ISSUE TITLE
Mini map position always unchanged

### ISSUE THREAD

**Issue by AndreescuGabriel** [Vectron/mapwriter#14]
I`m having a bit of trouble setting my minimap to the right top corner, if set in M menu it stays in the desired position but after a game restart the minimap resets to the left top corner and the option ingame remains "unchanged". In minimap.cfg i cannot find a value relative to this config option.

p.s. tried to look into the code myself to see where this config is stored but could not found it (I`m not a Java programmer)

**Comment by Vectron** [comment]
is this on 1.8 or 1.7.10?

**Comment by AndreescuGabriel** [comment]
1.7.10

**Comment by Vectron** [comment]
the value in the config file, are the 4 margins.

    I:marginBottom=-1
    I:marginLeft=10
    I:marginRight=-1
    I:marginTop=10
