### ISSUE TITLE
Nether appears in Surface dimension [1.8]

### ISSUE THREAD

**Issue by Cadiducho** [Vectron/mapwriter#15]
So, I just update tu 2.2.9-Beta and when I load my world, my... nether? was rendered, but in surface world. In 2.2.5 nothing happend to me
[http://i.imgur.com/cO20lTb.png](http://i.imgur.com/cO20lTb.png)

**Comment by Vectron** [comment]
what version of forge are you using?

**Comment by Cadiducho** [comment]
confirmed for 11.14.3.1519 and 11.14.3.1521 on Multiplayer map

**Comment by Vectron** [comment]
could you try with the recomended forge version?

**Comment by Cadiducho** [comment]
On recommended forge version and 2.2.10 nether bugs dissapear but... Grass seems like dirt? 
http://i.imgur.com/OVZL0W4.jpg
http://i.imgur.com/c5YebIU.jpg
Also, in multiplayer map

**Comment by Vectron** [comment]
oke, something probably changed in latest forge version, i will check this out when i have my enviorment working again with the latest forge,

as for the grass showing as dirt will check that out 2.

**Comment by Cadiducho** [comment]
`as for the grass showing as dirt will check that out 2.`
I can't understand this S:
I've been searching and MapWriterBlockColours.txt 'dirt' and 'grass' has got the same value (ff866043) but in version 2.2.5 grass has a correct value (ff9b9b9b). Maybe some code error or whatever on src/main/java/mapwriter/BlockColourGen.java

**Comment by Vectron** [comment]
i think i have to find a other way to get the block colours becous it seems that using the icons ingame fails.

maybe i can get the uv info from the jsons or something, but i'm still finding out how minecraft works on that part now

**Comment by Vectron** [comment]
this should be fixed in the new version.

will leave this open for now, dont know if it also fixes the grass bug

**Comment by Cadiducho** [comment]
Nether bug fixed, grass; leaves etc. still bugged on 11.14.3.1450
http://i.imgur.com/dvqfXLB.png
I'll keep testing

**Comment by Vectron** [comment]
did you try deleting the old color files so the game regens them?

i'm unable to reproduce the dirt bug....

**Comment by Cadiducho** [comment]
Okey.... I'll try with Forge 1.8 - 11.14.4.1563, MapWriter 2.2.11 and I deleted /config folder... Now works fine. It seems that was my mistake. Sorry for the inconvenience! :)
