### ISSUE TITLE
Option button doesn't work on 1.8

### ISSUE THREAD

**Issue by Cadiducho** [Vectron/mapwriter#16]
Confirmed for 1.8-2.2.5 and 1.8-2.2.9-Beta
If I press M and open the map, and then press on [Options] it doesn't work

**Comment by Vectron** [comment]
delete the config file, and then relaunch the game. the file probably is corupt (or still the 1.7.10 version)

**Comment by Cadiducho** [comment]
Fixed removing old file config
Thanks!
