### ISSUE TITLE
Saving waypoint in non-default group changes group waypoint that map shows

### ISSUE THREAD

**Issue by UntouchedWagons** [Vectron/mapwriter#20]
I have a waypoint group specifically for Immersive Engineering's ore veins. So when I find an ore vein I want to save I open the full screen map, change the group shown to "ore veins", right click my cursor then set a waypoint. But then for some reason the group that the map shows changes to "none". This shouldn't happen.

I'm using MapWriter 2.1.10

**Comment by Vectron** [comment]
hmmm if you change the space to a _ it should be fixed.

i will fix this in the next version

**Comment by Vectron** [comment]
this is fixed in version 1.8 onward.
forge and mc are already on 1.9 so i'm not updating this in the 1.7.10 version.
