### ISSUE TITLE
Map writer 1.9 has poor default positioning.

### ISSUE THREAD

**Issue by tali713** [Vectron/mapwriter#28]
As you may or may not be aware, as of 1.9 minecraft places potion indicators in the upper righthand corner of the screen.  While I have temporarily changed my copy of map writer to provide a larger top margin, it would be ideal if this were either on by default, or if the top margin were expanded by the 16 (resolution adjusted) pixels necessary to accommodate the indicator bar when it is displayed.  Currently I use a static value of 25 rather than the default 10 pixels and it works perfectly regardless of UI size choice.  I would submit a patch but it would be better if it dynamically adjusted.  Alternatively, if there was a way to force minecraft to display those indicators below the mini-map, this would accomplish the same end.

**Comment by Vectron** [comment]
i'm kind of aware, and will make the default position a bit more to the left so the potion effects will be visable.
