### ISSUE TITLE
[mapwriter.tasks.Task:printException:50]: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Sasikaa** [Vectron/mapwriter#29]
My game is log spamming this:
[22:55:47] [Client thread/INFO] [STDERR]: [mapwriter.tasks.Task:printException:50]: java.lang.NullPointerException

And my game:
Any button press my keyboard, load the FULL map, and very hard exit. Press ESC button, escape the full map, but load again the full map. This mod is NOT usable this bug....

**Comment by Vectron** [comment]
what version of mapwriter, and forge are you using?

**Comment by Sasikaa** [comment]
Omg... My MW version is 1.8.9 newest, and my forge is .1808. 1.8.9!!!

**Comment by Vectron** [comment]
do you have not enough keys installed by any chance?

**Comment by Sasikaa** [comment]
Yes, Not Enough Keys install!!
This is my mod list:
agricraft-2.0.0a3.jar
archimedesshipsplus-MC1.8.9-INDEV-G.jar
ArmorPlus-1.6(1.8.9).jar
Aroma1997Core-1.8.9-1.0.3.4.b58.jar
AromaBackup-1.8.9-0.0.1.1.b26.jar
autopackager-1.6.0.jar
Bagginses-1.8.9-2.1.5b.jar
bdlib-1.10.0.31-mc1.8.9.jar
BetterAchievements-1.8.9-0.1.1.jar
BetterBuildersWands-0.5.3-1.8.9r91+7e8699b.jar
BiomeTweaker-1.8.9-2.0.184.jar
BloodMagic-1.8.9-2.0.0-20.jar
Bookshelf-API-1.8.9-2.3.7.jar
Botania-unofficial.r1.8-299.jar
BowInfinityFix-1.8.x-rv2.jar
buildcraft-7.2.5.jar
buildcraft-compat-7.2.1.jar
BuildingBricks-1.8.9-1.4.4.jar
Chameleon-1.8.9-1.1.1.jar
Charset-0.2.4-85343416c852285a595c4c6e.jar
Chisel-MC1.8.9-0.0.2.6.jar
chiselsandbits-8.7.jar
compactstorage-2.1-1.8.9-rc.jar
ComputerCraft1.78.jar
CorrelatedPotentialistics-0.2.1.jar
craftingtweaks-mc1.8.9-3.0.52.jar
craftnstar-1.8.9-0.3.1.jar
CraftTweaker-1.8.8-3.0.2.jar
CrissCross-1.8.9-1.3.9.2.jar
deepresonance-1.8.9-1.1.4beta23.jar
denseores-1.8-alpha-2.0.0.jar
Durability Show-1.8.9-2.1.2 (1).jar
DynamicSurroundings-1.8.9-2.0.5.6.jar
ElecCore-1.8.9-1.4.247.jar
EnderCore-1.8.9-0.3.0.13-beta.jar
EnderIO-1.8.9-3.0.0.20_alpha.jar
EnderTanks-1.8.9-1.2.1.jar
enderutilities-1.8.9-0.5.3.jar
ExtraBitManipulation-1.8.9-1.4.0 (1).jar
extrautils2-1.8.9-alpha-0.0.2.jar
ezstorage-1.8.9-1.2.6.jar
Fancy Fluid Storage-1.8.9-1.5.1.97.jar
FastLeafDecay-1.8-1.6.jar
flatcoloredblocks-mc1.8.9-v1.8.jar
fluxedsolars-1.9 (1).jar
Foundry-1.8.9-1.4.0.0.jar
FTBLib-1.8.9-2.0.2.jar
FTBUtilities-1.8.9-2.0.2.jar
Furnus-1.8.9-1.73.jar
generators-0.9.19.9-mc1.8.9.jar
graves-1.8.9-b47-universal.jar
hopperducts-mc1.8.8-1.4.6.jar
HydCraft-1.8.9-3.1.81-universal.jar
IGW-Mod-1.8.9-1.2.4-4-universal.jar
intangible-1.8.9-0.0.25.jar
inventorysorter-1.8.9-0.7.7+27.jar
InventoryTweaks-1.60-40.jar
ironchest-1.8.9-6.0.125.770.jar
itemscroller-1.8.9-0.2.3.jar
JAPTA-1.4.1.jar
jei_1.8.9-2.28.12.180.jar
JEIAddons_1.8.9-0.12.0.57.jar
journeymap-1.8.9-5.1.5-unlimited.jar
JustEnoughResources-1.8.9-0.4.0.jar
k4lib-1.8.9-1.0.18-universal.jar
kleeracer-1.0.jar
LLOverlayReloaded-1.0.7-mc1.8.9.jar
malisiscore-1.8.9-2.1.3.jar
malisisdoors-1.8.9-3.1.3.jar
Mantle-1.8.9-0.9.2.jar
mcjtylib-1.8.9-1.8.1beta10.jar
MCMultiPart-1.0.9-universal.jar
MmmMmmMmmMmm-1.9b.jar
ModLister-1.8.9-1.0.7.jar
ModularPowersuits-1.8.9-0.11.0-003.jar
MouseTweaks-2.6.2-mc1.8.9.jar
movingworld-MC1.8.9-INDEV-H-full.jar
MrCrayfishFurntiureModv3.6.1(1.8.9).jar
Neat 1.1-3.jar
NeoTech-1.8.9-2.4.4.jar
NoMoreRecipeConflict-0.3(1.8.X).jar
NotEnoughKeys-1.8.9-3.0.0b1-dev-universal.jar
notenoughwands-1.8.9-1.2.9.jar
Numina-0.5.0-001.jar
OptiFine_1.8.9_HD_U_H2.jar
OreDictionaryConverter-1.7.2.jar
PneumaticCraft-1.8.9-1.13.8-12-universal.jar
ProgressiveAutomation-1.8.9-1.6.35.jar
quantumflux-1.8.9-2.0.1.jar
QuantumStorage-1.8.9-2.0.3 (1).jar
RandomThings-MC1.8.9-3.6.6.jar
RebornCore-1.8.9-1.4.3.20-universal.jar
rftools-1.8.9-4.23beta35.jar
RoguelikeDungeons-1.8.9-1.4.5 (1).jar
RTG-1.8.9-0.1.0.jar
SciAPI-1.2.0.1.jar
ShadowMC-1.8.9-3.0.0-SNAPSHOT.jar
ShetiPhianCore-1.8.9-3.1.0.jar
simplelabels-1.8.9-0.0.4.jar
simpleretrogen-1.8.9-2.2.2+3.jar
SoulShards-TOW-1.8.9-2.2.8-16.jar
StorageDrawers-1.8.9-2.6.3.jar
StorageNetwork-1.8.9-1.9.0.jar
Substratum-1.8.9-1.1.0.1.jar
SuperMultiDrills-1.8.9-1.3.0-beta4-26.jar
tchelper-1.8.9-1.2 (1).jar
TConstruct-1.8.9-2.2.1.jar
Thaumcraft-1.8.9-5.2.4.jar
ThaumicInfusion-1.8.9-4.86.jar
thutcore-1.8.9-2.4.5.jar
thuttech-2.3.4.jar
VeinMiner-1.8.9_0.31.4.unknown.jar
villagebox-beta 0.2.0.jar
villagebox-beta 0.3.0.jar
Waila-1.6.0-B3_1.8.8.jar
warpbook-1.8.9_2.0.43.jar
Wawla-1.8.9-1.1.4.171.jar
waypoints-1.8.9-1.2.0c.jar

**Comment by Vectron** [comment]
the problem probably is a update to the not enough keys api, try and remove it and see if the error is still there.

i will probably remove suport for it becouse it changes the api to often.
