### ISSUE TITLE
To many Textures "I think" Bug (What killed OPIS for us.

### ISSUE THREAD

**Issue by KaneHart** [Vectron/mapwriter#3]
This is a bug that sadly also ruined Opis for our server. I hoped it was not an issue with plain Mapwriter but it is.

http://pastebin.com/pWbqCa8p

I finally had time to give it a shot was going to try your little radar addition for the server side :(

**Comment by Vectron** [comment]
are you using a certain pack or so where i can test it with.
i only seen this crash in posts but never on my own machine

**Comment by KaneHart** [comment]
I don't have a public pack but if you use MCUpdater:
http://files.mcupdater.com/MCUpdater-recommended.jar

And add this URL:
http://updater.stonelegion.com/minecraft.xml

And use the Private server and then add the mapwriter to the mods folder it will happen to you. 

Sadly it's a tad complex.

It seems to happen when the texture sheet reaches a certain size. Depending how many mods I have if I remove a bunch it will work if I keep low amount texture mods it's fine but once I add to many to make the main sheet too big it seems to bust it.

**Comment by Vectron** [comment]
have a fix that will prevent the crash from happening.

only downside is that the block(s) on wich it fails won't render at all.

if you're oke with that you can download it here: 
https://www.dropbox.com/s/8mdifbokax1eoxy/MapWriter-1.7.10-2.1.5-Beta.jar?dl=0

**Comment by KaneHart** [comment]
Thank you. Sadly it seems to just scramble everything to hell. Example screenshit:
http://i.imgur.com/PL4xVbp.png
You can see where it worked one time I think it was another version tbh posted on MC Forums a long time ago. Sadly lost it. But you can see the working area vs the red blood looking stuff now. 

Thank you for looking into it, it means a lot.

**Comment by KaneHart** [comment]
Just to add to this I removed my downloads folder recently cleaning my SSD Crap! But I think It was jake_stafunk version that worked before.

http://www.fansana.de/download/MapWriter-1.7.10.jar

Sadly I can't get his site working but maybe he had found a fix or did something in another method.

**Comment by Vectron** [comment]
could you send me your log of the test?

i asked jake what he changed compared to my git, but he said it was about the same.... so i'm not sure what the difference is....

**Comment by Vectron** [comment]
oke, second try to fix the bugs:
https://www.dropbox.com/s/s4mzbyfuozc6pbu/MapWriter-1.7.10-2.1.5-Beta-2.jar?dl=0

**Comment by KaneHart** [comment]
Sorry about the delay friend. I been away for a few days as my house had lost AC.
Looks like you fixed it :)
http://i.imgur.com/3uKf9ry.png

Now I have to try the MP addon :)

**Comment by Vectron** [comment]
good, then i can close this bug finally ^^
