### ISSUE TITLE
1.9 Forge 1839 GuiOpenEvent

### ISSUE THREAD

**Issue by ryanjo1982** [Vectron/mapwriter#30]
Client crashes while loading the pack. Does not event make it to the minecraft window.

http://paste.ee/p/fuHXS

Everything is listed in the file that should be able to help you duplicate the error.

**Comment by Vectron** [comment]
rollback a few forge versions (my last build is against forge 12.16.0.1809-1.9), or wait untill i update to the latest forge version.
