### ISSUE TITLE
Top Right Map in wrong position

### ISSUE THREAD

**Issue by CA2020** [Vectron/mapwriter#36]
On version MapWriter-1.9-2.4.17 the Top Right position for the Minimap got somehow broken and it doesn't place it really on the top top.

**Comment by Vectron** [comment]
i'm aware of this, i moved it a bit down to make the map not go over the effects bars.

i'm working on a way for users to position the map where ever they want. so please bare with it for now :)

**Comment by CA2020** [comment]
Yes after a while of playing I realized that could be the reason. Thanks and yes a feature to position freely, or at least to have the option to place it again right in the corner would be great. I personally don't need to see the potions effects on top right, but I see why you did the change ;)

Thanks a lot.

**Comment by Vectron** [comment]
i'm closing this, in the latest version (2.4.18) you can position the map wherever you want.
