### ISSUE TITLE
[1.9] Crash

### ISSUE THREAD

**Issue by tanto259** [Vectron/mapwriter#39]
When starting world, minecraft crashed.
Log: [https://paste.ee/p/O1SoZ](https://paste.ee/p/O1SoZ)

**Comment by Vectron** [comment]
could you send me the fml-client-latest.log and latest.log after the crash happened

**Comment by tanto259** [comment]
Here it is: [http://pastebin.com/0UNvGXdj](http://pastebin.com/0UNvGXdj)
Also, I just updated the mod to the latest 2.4.19 version with the latest forge version and I couldn't replicate the issue.
Thanks anyway.
