### ISSUE TITLE
Crash with both the 2.1.4 version and the 2.1.6 version

### ISSUE THREAD

**Issue by NullMagic** [Vectron/mapwriter#4]
Alright, needless to say I was ecstatic to see a new version of mapwriter, and despite this minor setback I'm still quite pleased to see that someone has taken up the production of it once more. Unfortunately on loading I encountered a crash which I'm hoping you can get to the bottom of.

here's the Error Report: http://pastebin.com/4w8rZ9gi

Now, I'm not entirely sure the crash has to do with Mapwriter, however the log said that mapwriter was doing something with block Color generation right before the crash occurred and removing the mod eliminated the crash, so I'm hoping that this is the right place to report this one.

Anyway, I hope this can be figured out so that I can get back to reveling in full screen map glory, thanks for your work!

**Comment by clou44** [comment]
I have also experienced and heard reports of similar crashes. Will attempt to get a log soon.

**Comment by Vectron** [comment]
I have an idea why this happens. Will fix it the next time
