### ISSUE TITLE
Crash client.

### ISSUE THREAD

**Issue by Pilad** [Vectron/mapwriter#5]
Crash http://pastebin.com/qqShaF29
Crashlog http://pastebin.com/XNW8AqbK

**Comment by Vectron** [comment]
what modpack are you using?

**Comment by maxlowry123** [comment]
I am also having issues, not sure if it is the exact same thing.
I can not get the game to start when I have mapwriter. It starts by itself and I have not tested to see which mod is causing it to crash yet.
Full Log http://paste.ee/p/ZzuGI (List of mods starts at line 71)
Crash Report: http://paste.ee/p/ecCKM
This is not an official modpack it is just a group of mods I want to play with.

**Comment by Vectron** [comment]
i'll add a update with a null check, but i wouldnt mind if you could post me the log after you updated so i can understand why it crashes.
