### ISSUE TITLE
incorrect version checking for 1.12.2

### ISSUE THREAD

**Issue by Zygus42** [Vectron/mapwriter#64]
MapWriter-1.12.2-2.8.0.jar
forge-1.12.2-14.23.0.2491-installer-win

When you start minecraft gives the msg:
The mods listed below can't run in Minecraft version 1.12.2
Mapwriter requires Minecraft between 1.12 and 1.12.1, 1.12.2 (inclusive)
Try to find an update or remove MapWriter

**Comment by Vectron** [comment]
yeah something seems to have changed between 1.12.1 and 1.12.2 that i missed, i will update this asap
