### ISSUE TITLE
Biomes O Plenty-Solved! UPDATE MOD PLS - MapWriterBlockColourOverrides <<< was the culprit

### ISSUE THREAD

**Issue by lilgandhi1199** [Vectron/mapwriter#65]
Redwood Forest leaves are greyed out

**Comment by lilgandhi1199** [comment]
I can provide you with a 12mb map where you respawn in that biome to test yourself
but it is version 7.0.1.2302 too

**Comment by lilgandhi1199** [comment]
Sorry just realized there a lot of tree leaves that are greyed out. There are also some that seem to work fine. I'm not sure how you could fix this...

**Comment by Vectron** [comment]
you could add overrides for different blocks. (there should be a over MapWriterBlockColourOverrides.txt in your minecraft config folder)

**Comment by lilgandhi1199** [comment]
And perhaps once I've created it you could mention the pastebin for my overrides of bop (I see you've already added some) or just upload it with yours for everyone to use

**Comment by lilgandhi1199** [comment]
EDIT: It looks like you did everything for bop and natura! I'm getting an error I just noticed though and perhaps that's the source of the problem!
https://pastebin.com/raw/geX0e9pG

**Comment by lilgandhi1199** [comment]
Okay! It was just simply that all BiomesOPlenty need to be changed lowercase to biomesoplenty
And it looks like you forgot to make the change in that override file too! :D

**Comment by lilgandhi1199** [comment]
I'll let you close it actually once you've fixed it for everyone else
