### ISSUE TITLE
Request: Toggle water depth? prismarine temples...

### ISSUE THREAD

**Issue by lilgandhi1199** [Vectron/mapwriter#66]
Hey I wonder if you could add a toggle so I can't easily see the bottom of my oceans and find every single prismarine temple in my world without trying!

https://imgur.com/a/6x1Bw

**Comment by Vectron** [comment]
it's not realy a toggle problem. you just see the depth difference.

i'm not 100% sure it would work but try and add water to the overrides file and make it opaque (color starting with ff, somethings like: block minecraft:water * ff2f43f4)

**Comment by lilgandhi1199** [comment]
That worked perfectly! Thanks for figuring that one out for me 🗡
