### ISSUE TITLE
Client Crash when attempting to load waypoints

### ISSUE THREAD

**Issue by beesyndicate** [Vectron/mapwriter#67]
When conecting to a server after you have set way points the client crashes 
If you delete the folder  

C:\Users\user\AppData\Roaming\.minecraft(or in my case .technic)\modpacks\modpackname\saves\servername\

you can then reconect to the server without the client crashing.

https://pastebin.com/FcHgw3xv

**Comment by beesyndicate** [comment]
Note this happens when the waypoints are shown in the world

**Comment by Vectron** [comment]
i'll see if i can reproduce this. and add a null check so we dont crash any more

**Comment by beesyndicate** [comment]
Thank you!

**Comment by beesyndicate** [comment]
I was able to reproduce this today on a different PC on a different MC account. In case you need it and or it makes life easier for you here is the location of the mod pack https://www.technicpack.net/modpack/mittzfitz-testing.1134793 
and the test server is beesyndicate.ddns.net:415

**Comment by beesyndicate** [comment]
Hello again Vectron
I know that for most people these mods are a hobby and very understandably. many many other things in life take priority over them.
I was just wondering how this fix was going and if you have any sort of ETA?
