### ISSUE TITLE
Full localization support

### ISSUE THREAD

**Issue by Adaptivity** [Vectron/mapwriter#7]
There a lot of hardcoded localization inside code. Can you move it out, so translators can translate it?

**Comment by Vectron** [comment]
will put it on my todo list.

**Comment by Vectron** [comment]
i think i have every thing localized now.
(only in the 1.8 version, and i'm not backporting it to 1.7.10)

**Comment by Adaptivity** [comment]
Thank you. I'm not going to translate it now since nobody uses 1.8 and I too. Maybe when 1.8 will become more popular.
